"""
Word Test Case Document Generator.

Creates a structured .docx document containing:
- Test case metadata (name, description, preconditions)
- Step-by-step table (Step #, Action, Data, Expected Result, Status)
- Embedded screenshots from actual execution
- Summary statistics
"""

import logging
from datetime import datetime
from pathlib import Path
from typing import Optional

from docx import Document
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Cm, Inches, Pt, RGBColor

from models.schemas import StepStatus, TestCaseResult

logger = logging.getLogger(__name__)


class DocxGenerator:
    """Generates Word test case documents from execution results."""

    def __init__(self, output_dir: str = "output/testcases"):
        self.output_dir = output_dir
        Path(output_dir).mkdir(parents=True, exist_ok=True)

    def generate(self, test_result: TestCaseResult) -> str:
        """
        Generate a Word document from test execution results.

        Returns the file path of the generated document.
        """
        tc = test_result.test_case
        doc = Document()

        self._add_title(doc, tc.name)
        self._add_metadata(doc, test_result)
        self._add_steps_table(doc, test_result)
        self._add_summary(doc, test_result)

        safe_name = tc.name.replace(" ", "_")[:50]
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"TC_{safe_name}_{timestamp}.docx"
        filepath = Path(self.output_dir) / filename

        doc.save(str(filepath))
        logger.info("Generated test case document: %s", filepath)
        return str(filepath)

    def _add_title(self, doc: Document, title: str) -> None:
        """Add document title."""
        heading = doc.add_heading(title, level=0)
        heading.alignment = WD_ALIGN_PARAGRAPH.CENTER

        subtitle = doc.add_paragraph()
        subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = subtitle.add_run(
            f"Generated by Self-Healing Autonomous Test Agent\n"
            f"{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
        )
        run.font.size = Pt(10)
        run.font.color.rgb = RGBColor(128, 128, 128)

    def _add_metadata(self, doc: Document, result: TestCaseResult) -> None:
        """Add test case metadata section."""
        tc = result.test_case

        doc.add_heading("Test Case Information", level=1)
        table = doc.add_table(rows=0, cols=2)
        table.style = "Light Grid Accent 1"

        metadata = [
            ("Test Case ID", tc.id),
            ("Description", tc.description),
            ("Preconditions", tc.preconditions or "None"),
            ("Target URL", tc.target_url),
            ("Source File", tc.source_file or "N/A"),
            ("Total Steps", str(len(tc.steps))),
            ("Overall Status", result.overall_status.value.upper()),
        ]

        for label, value in metadata:
            row = table.add_row()
            row.cells[0].text = label
            row.cells[1].text = value
            # Bold the label
            for paragraph in row.cells[0].paragraphs:
                for run in paragraph.runs:
                    run.bold = True

        doc.add_paragraph()

    def _add_steps_table(self, doc: Document, result: TestCaseResult) -> None:
        """Add the step-by-step execution table with embedded screenshots."""
        doc.add_heading("Test Steps", level=1)

        table = doc.add_table(rows=1, cols=6)
        table.style = "Light Grid Accent 1"
        table.alignment = WD_TABLE_ALIGNMENT.CENTER

        # Header row
        headers = ["Step #", "Action", "Input Data", "Expected Result", "Status", "Locator"]
        for i, header in enumerate(headers):
            cell = table.rows[0].cells[i]
            cell.text = header
            for paragraph in cell.paragraphs:
                paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
                for run in paragraph.runs:
                    run.bold = True
                    run.font.size = Pt(9)

        # Step rows
        for step_result in result.step_results:
            step = step_result.step_input
            row = table.add_row()

            row.cells[0].text = str(step.step_number)
            row.cells[1].text = step.intent
            row.cells[2].text = step.input_data or "—"
            row.cells[3].text = step.expected_result
            row.cells[4].text = step_result.status.value.upper()
            row.cells[5].text = (
                step_result.locators_used.primary.value
                if step_result.locators_used
                else "N/A"
            )

            # Color-code the status cell
            status_cell = row.cells[4]
            color = self._status_color(step_result.status)
            for paragraph in status_cell.paragraphs:
                for run in paragraph.runs:
                    run.font.color.rgb = color
                    run.bold = True
                    run.font.size = Pt(9)

            # Set font size for all cells
            for cell in row.cells:
                for paragraph in cell.paragraphs:
                    for run in paragraph.runs:
                        if not run.bold:
                            run.font.size = Pt(9)

        doc.add_paragraph()

        # Embed screenshots per step
        self._add_screenshots_section(doc, result)

    def _add_screenshots_section(self, doc: Document, result: TestCaseResult) -> None:
        """Add a section with before/after screenshots for each step."""
        doc.add_heading("Execution Screenshots", level=1)

        for step_result in result.step_results:
            step = step_result.step_input
            doc.add_heading(
                f"Step {step.step_number}: {step.intent}", level=2
            )

            if step_result.screenshot_before and Path(step_result.screenshot_before).exists():
                doc.add_paragraph("Before:")
                try:
                    doc.add_picture(step_result.screenshot_before, width=Inches(5.5))
                except Exception as exc:
                    doc.add_paragraph(f"[Screenshot could not be embedded: {exc}]")

            if step_result.screenshot_after and Path(step_result.screenshot_after).exists():
                doc.add_paragraph("After:")
                try:
                    doc.add_picture(step_result.screenshot_after, width=Inches(5.5))
                except Exception as exc:
                    doc.add_paragraph(f"[Screenshot could not be embedded: {exc}]")

            if step_result.error_message:
                error_para = doc.add_paragraph()
                run = error_para.add_run(f"Error: {step_result.error_message}")
                run.font.color.rgb = RGBColor(200, 0, 0)
                run.font.size = Pt(9)

    def _add_summary(self, doc: Document, result: TestCaseResult) -> None:
        """Add execution summary section."""
        doc.add_heading("Execution Summary", level=1)

        summary_items = [
            f"Total Steps: {len(result.step_results)}",
            f"Passed: {result.passed_steps}",
            f"Failed: {result.failed_steps}",
            f"Self-Healed: {result.healed_steps}",
            f"Total Duration: {result.total_duration_ms:.0f} ms",
            f"Total Healing Attempts: {result.total_healing_attempts}",
            f"Overall Status: {result.overall_status.value.upper()}",
        ]

        for item in summary_items:
            doc.add_paragraph(item, style="List Bullet")

    def _status_color(self, status: StepStatus) -> RGBColor:
        """Return an RGB color for a step status."""
        colors = {
            StepStatus.PASSED: RGBColor(0, 150, 0),
            StepStatus.FAILED: RGBColor(200, 0, 0),
            StepStatus.HEALED: RGBColor(200, 150, 0),
            StepStatus.RUNNING: RGBColor(0, 100, 200),
            StepStatus.PENDING: RGBColor(128, 128, 128),
            StepStatus.SKIPPED: RGBColor(128, 128, 128),
        }
        return colors.get(status, RGBColor(0, 0, 0))
