"""
Playwright Test Script Generator.

Generates clean, PEP8-compliant Python Playwright test scripts from
executed test case results. The generated scripts include setup,
teardown, and the ranked locators discovered during execution.
"""

import logging
from datetime import datetime
from pathlib import Path
from textwrap import dedent, indent

from models.schemas import (
    ActionType,
    LocatorSet,
    StepStatus,
    TestCase,
    TestCaseResult,
    TestStepResult,
)

logger = logging.getLogger(__name__)


class ScriptGenerator:
    """Generates Python Playwright automation scripts from test results."""

    def __init__(self, output_dir: str = "output/scripts"):
        self.output_dir = output_dir
        Path(output_dir).mkdir(parents=True, exist_ok=True)

    def generate(self, test_result: TestCaseResult) -> str:
        """
        Generate a complete Playwright test script from execution results.

        Returns the file path of the generated script.
        """
        tc = test_result.test_case
        safe_name = self._safe_name(tc.name)
        filename = f"test_{safe_name}.py"
        filepath = Path(self.output_dir) / filename

        script = self._build_script(test_result)
        filepath.write_text(script, encoding="utf-8")

        logger.info("Generated script: %s", filepath)
        return str(filepath)

    def _build_script(self, test_result: TestCaseResult) -> str:
        """Assemble the full script content."""
        tc = test_result.test_case
        safe_name = self._safe_name(tc.name)
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        header = dedent(f'''\
            """
            Auto-Generated Playwright Test Script
            ======================================
            Test Case : {tc.name}
            Description: {tc.description}
            Target URL : {tc.target_url}
            Generated  : {timestamp}
            Source     : {tc.source_file or "N/A"}

            This script was generated by the Self-Healing Autonomous Test Agent.
            Locators are ranked by reliability (primary -> secondary -> tertiary).
            """

            import re
            from playwright.sync_api import Playwright, sync_playwright, expect


        ''')

        setup = dedent(f'''\
            def run(playwright: Playwright) -> None:
                """Execute the test case."""
                browser = playwright.chromium.launch(headless=False)
                context = browser.new_context(
                    viewport={{"width": 1920, "height": 1080}},
                )
                page = context.new_page()

                # Navigate to target application
                page.goto("{tc.target_url}")
                page.wait_for_load_state("networkidle")

        ''')

        steps_code = self._build_steps(test_result)

        teardown = dedent('''\

                # --- Teardown ---
                context.close()
                browser.close()


            with sync_playwright() as playwright:
                run(playwright)
        ''')

        return header + setup + steps_code + teardown

    def _build_steps(self, test_result: TestCaseResult) -> str:
        """Generate code for each test step with locator comments."""
        lines = []

        for step_result in test_result.step_results:
            step = step_result.step_input
            locators = step_result.locators_used

            lines.append(f"    # Step {step.step_number}: {step.intent}")
            lines.append(f"    # Expected: {step.expected_result}")

            if locators:
                lines.append(f"    # Element: {locators.element_name}")
                lines.append(self._build_action_code(step, locators))

                # Add commented-out backup locators
                ranked = locators.ranked()
                if len(ranked) > 1:
                    lines.append("    # --- Backup locators (self-healing) ---")
                    for i, loc in enumerate(ranked[1:], start=2):
                        backup_code = self._locator_to_code(loc)
                        lines.append(
                            f"    # Backup {i} ({loc.strategy.value}): {backup_code}"
                        )
            else:
                lines.append(f"    # WARNING: No locators identified for this step")
                lines.append(f'    # TODO: Manually add locator for "{step.intent}"')

            if step_result.status == StepStatus.HEALED:
                lines.append(
                    f"    # NOTE: Self-healed — primary locator failed, "
                    f"used backup #{step_result.locator_used_index + 1}"
                )

            lines.append("")

        return "\n".join(lines)

    def _build_action_code(self, step, locators: LocatorSet) -> str:
        """Generate the Playwright action code for a step."""
        primary = locators.primary
        loc_code = primary.to_playwright()

        match step.action_type:
            case ActionType.CLICK:
                return f"    {loc_code}.click()"
            case ActionType.FILL:
                data = step.input_data or ""
                return f'    {loc_code}.fill("{data}")'
            case ActionType.SELECT:
                data = step.input_data or ""
                return f'    {loc_code}.select_option("{data}")'
            case ActionType.CHECK:
                return f"    {loc_code}.check()"
            case ActionType.UNCHECK:
                return f"    {loc_code}.uncheck()"
            case ActionType.HOVER:
                return f"    {loc_code}.hover()"
            case ActionType.NAVIGATE:
                url = step.input_data or step.page_url or ""
                return f'    page.goto("{url}")'
            case ActionType.WAIT:
                ms = step.input_data or "2000"
                return f"    page.wait_for_timeout({ms})"
            case ActionType.ASSERT_VISIBLE:
                return f"    expect({loc_code}).to_be_visible()"
            case ActionType.ASSERT_TEXT:
                return f'    expect({loc_code}).to_contain_text("{step.expected_result}")'
            case ActionType.ASSERT_VALUE:
                return f'    expect({loc_code}).to_have_value("{step.expected_result}")'
            case ActionType.SCREENSHOT:
                return f'    page.screenshot(path="step_{step.step_number}.png")'
            case _:
                return f"    # TODO: Implement action '{step.action_type.value}'"

    def _locator_to_code(self, locator) -> str:
        """Convert a locator to its Playwright code representation."""
        return locator.to_playwright()

    def _safe_name(self, name: str) -> str:
        """Convert a test case name to a safe Python identifier."""
        import re
        safe = re.sub(r"[^a-zA-Z0-9_]", "_", name.lower())
        safe = re.sub(r"_+", "_", safe).strip("_")
        return safe[:60]
